= Requesting and installing Let's Encrypt Certificates for OpenShift 4

== Overview

For any OpenShift cluster it is suggested to use proper certificates to secure the routes and API endpoints.

In OpenShift 3 certificates are usually added during the installation process by modifying the `/etc/ansible/hosts` file. In OpenShift 4 however there is no mechanism to provide certificates during the installation process. Adding certificates is considered a post-installation task.

Luckily in OpenShift 4 it is very easy to apply certificates after the installation has completed.

This document walks through using *Let's Encrypt* to provision certificates for your cluster. You will need to know the API endpoint URL and the Wildcard Domain for your router(s).

== Installing acme.sh

If you already have certificates for your domains you may skip this step and go straight to <<installing>>.

In order to request Let's Encrypt certificates we will use the *acme.sh* client. This client makes it very easy to request and update certificates.

. Clone the `acme.sh` GitHub repository.
+
[source,sh]
----
cd $HOME
git clone https://github.com/neilpang/acme.sh
cd acme.sh
----

. Update the file `$HOME/acme.sh/dnsapi/dns_aws.sh` with your AWS access credentials. This is necessary because you are requesting a certificate for wildcard domain and Let's Encrypt needs a way to validate that you are the owner of the wildcard domain.
+
Open the file in your favorite text editor and then add your AWS credentials. You will also need to remove the comment (`#`) before these two lines. The top of the file should look like this:
+
[source,sh]
----
#!/usr/bin/env sh

#
AWS_ACCESS_KEY_ID="YOUR ACCESS KEY"
#
AWS_SECRET_ACCESS_KEY="YOUR SECRET ACCESS KEY"

#This is the Amazon Route53 api wrapper for acme.sh

[...]
----

== Requesting Certificates

. To make things a bit easier set two environment variables. The first variable should point to your API Endpoint. Use the `oc` CLI to find the API Endpoint URL.
+
[source,sh]
----
oc whoami --show-server
----
+
.Sample Output
[source,texinfo]
----
https://cluster-e954-api.e954.ocp4.opentlc.com:6443
----

. Now set the variable LE_API to the fully qualified domain name:
+
[source,sh]
----
export LE_API=cluster-e954-api.e954.ocp4.opentlc.com
----

. Set the second variable LE_WILDCARD to your Wildcard Domain for example:
+
[source,sh]
----
export LE_WILDCARD=apps.cluster-e954.e954.ocp4.opentlc.com
----

. Run the acme.sh script
+
[source,sh]
----
${HOME}/acme.sh/acme.sh --issue -d ${LE_API} -d *.${LE_WILDCARD} --dns dns_aws
----

. It is usually a good idea to move the certificates from the `acme.sh` default path to a well known directory. So use the `--install-cert` option of the `acme.sh` script to copy the certificates to `$HOME/certificates`.

+
[source,sh]
----
${HOME}/acme.sh/acme.sh --install-cert -d ${LE_API} -d *.${LE_WILDCARD} --cert-file ${HOME}/certificates/cert.pem --key-file ${HOME}/certificates/key.pem --fullchain-file ${HOME}/certificates/fullchain.pem --ca-file ${HOME}/certificates/ca.cer
----

[[installing]]
== Installing Certificates for the Router

The Router expects the certificates in a `Secret`. This secret needs to be created in the project `openshift-ingress`.

. Use the following command to create the secret - and if you have existing certificates make sure to provide the path to your certificates instead.
+
[source,sh]
----
oc create secret generic router-certs --from-file=tls.crt=${HOME}/certificates/fullchain.pem --from-file=tls.key=${HOME}/certificates/key.pem -n openshift-ingress
----

. Now update the Custom Resource for your router. The default custom resource is of type `ClusterIngress`, is named `default` and is located in the `openshift-ingress-operator` project. Note that this project is different from where you created the secret earlier.

+
[source,sh]
----
oc patch clusteringress default -n openshift-ingress-operator --patch='{"spec": { "defaultCertificateSecret": "router-certs" }}' --type=merge
----

. This is all you need to do. After you update the ClusterIngress object the OpenShift ingress operator notices that the custom resource has changed and therefore re-deploys the router.

. You now have proper certificates on the router - and this includes both custom applications as well as the Web Console for your OpenShift Cluster.

== Installing Certificates for the API Endpoint

This will be added in a later version of this document.
